on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  NODE_VERSION: "14.x"
  CONVEX_ADMIN_KEY: ${{ secrets.CONVEX_ADMIN_KEY }}
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"

      - name: Install packages
        run: yarn

      - name: Install Vercel CLI
        run: yarn global add vercel@latest

      - name: Setting up Vercel Project
        run: |
          vercel link -y --project=convex-chat --token=${{secrets.VERCEL_TOKEN}}
          vercel pull -y --environment=preview --token=${{secrets.VERCEL_TOKEN}}

      - name: Updating .env.local file
        env:
          NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}
          NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
          GITHUB_ID: ${{secrets.GIT_ID}}
          GITHUB_SECRET: ${{secrets.GIT_SECRET}}

        run: |
          echo "NEXTAUTH_SECRET=$NEXTAUTH_SECRET" >> .env.local
          echo "NEXTAUTH_URL=$NEXTAUTH_URL" >> .env.local
          echo "GITHUB_ID=$GITHUB_ID" >> .env.local
          echo "GITHUB_SECRET=$GITHUB_SECRET" >> .env.local

      - name: Updating convex
        run: npx convex push

      - name: Build project
        run: |
          vercel build --token=${{secrets.VERCEL_TOKEN}}
          vercel deploy --prebuilt --token=${{secrets.VERCEL_TOKEN}}
